# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-06 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'yython'), ('dj', 'Django'), ('ui', 'UI'), ('rest', 'REST API')], max_length=200)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('mng', 'Morning'), ('aftn', 'Afternoon'), ('evng', 'Evening'), ('ngt', 'Night')], max_length=200)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'Hyderabad'), ('bang', 'Banglore'), ('chen', 'Chennai'), ('pune', 'Pune')], max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('course_dur', models.IntegerField()),
                ('course_fee', models.IntegerField()),
                ('start_date', models.DateField(max_length=100)),
                ('start_time', models.TimeField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('trainer_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('feedback', models.TextField(max_length=100)),
            ],
        ),
    ]
